version: '3'
services:
  mysql:
    image: mysql:latest
    volumes:
      - "./data/db:/var/lib/mysql"
    restart: "no"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password

  mailcatcher:
     image: schickling/mailcatcher
     restart: "no"
     ports:
       - "1025:1025"
       - "1080:1080"
     environment:
       MAILCATCHER_PORT: 1025

  memcached:
    image: memcached:latest
    restart: "no"

  elasticsearch:
    image: elasticsearch:5
    restart: "no"
    environment:
      ES_JAVA_OPTS: "-Xms750m -Xmx750m"
    ports:
      - "9200:9200"
    volumes:
      - "./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
      - "./config/elasticsearch/plugins:/usr/share/elasticsearch/plugins"

  phpfpm:
    image: 10up/phpfpm
    depends_on:
      - mysql
      - memcached
      - elasticsearch
    volumes:
      - "./wordpress:/var/www/html/bedrock"
      - "./config/php-fpm/php.ini:/usr/local/etc/php/php.ini"
      - "./config/php-fpm/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
    restart: "no"

  nginx:
    depends_on:
      - phpfpm
    ports:
      - "80:80"
      - "443:443"
    image: nginx:latest
    volumes:
      - "./wordpress:/var/www/html/bedrock"
      - "./config/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./config/certs:/etc/nginx/certs"
      - "./logs/nginx:/var/log/nginx"
    restart: "no"

  node:
    image: node:6
    working_dir: /var/www/html/municipio
    volumes:
      - "./wordpress/web/app/themes/municipio:/var/www/html/municipio"
    restart: "no"
